version: "2.1"

services:
  db:
    container_name: streetfair_postgres_test
    image: mdillon/postgis:10-alpine
    mem_limit: 500m
    networks:
      - streetfair_stack
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: streetfair
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: streetfair
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 1s
      timeout: 3s
      retries: 30

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    container_name: bookmark-grafana
    network_mode: "bridge"
    depends_on:
      - prometheus
      - prometheus-pushgateway
  
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    container_name: bookmark-prometheus
    network_mode: "bridge"
  prometheus-pushgateway:
    image: prom/pushgateway
    container_name: bookmark-pushgateway
    expose:
      - 9091
    ports:
      - "9091:9091"
  
  wait:
    container_name: wait-db
    image: "waisbrot/wait"
    restart: "no"
    networks:
      - streetfair_stack
    environment:
      TARGETS: "db:5432"
      TIMEOUT: 60
    depends_on:
      - db

networks: {streetfair_stack: {}}
