name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

env:
  ENVIRONMENT: production

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Test envs
        run: echo ${{env.ENVIRONMENT}}
      
      - name: Test new enviroment
        env:
          ENVIRONMENT: banana
        run: echo ${{env.ENVIRONMENT}}

      - name: Test get environemnt
        run: echo ${{env.ENVIRONMENT}}

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: latest

      - name: Execute Go test
        run: |
          go test $(go list ./...) -coverprofile=coverage.out -json > report.json
          go tool cover -func=coverage.out

      - name: Go Vet
        run: go vet $(go list ./...) > govet-report.out

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
